# Generated by Django 3.2.9 on 2021-12-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burger',
            name='rasmi',
            field=models.ImageField(upload_to=''),
        ),
    ]
