# Generated by Django 2.2.16 on 2021-12-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aloqa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=300)),
                ('massage', models.TextField(default=0)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
